export const TOGGLE_BURGER = 'TOGGLE_BURGER'
export const TOGGLE_DARK_MODE = 'TOGGLE_DARK_MODE'

export const FETCH_PROVINCE_REQ = 'FETCH_PROVINCE_REQ'
export const FETCH_PROVINCE_SUCCESS = 'FETCH_PROVINCE_SUCCESS'
export const FETCH_PROVINCE_ERROR = 'FETCH_PROVINCE_ERROR'