export const TOGGLE_BURGER = 'TOGGLE_BURGER'
export const FETCH_MODE_REQ = 'FETCH_MODE_REQ'
export const FETCH_MODE_SUCCESS = 'FETCH_MODE_SUCCESS'
export const FETCH_MODE_FAILURE = 'FETCH_MODE_FAILURE'